FROM ubuntu/squid:latest

ARG AGENTD_VERSION=dev
ARG AGENTD_COMMIT=unknown

LABEL org.opencontainers.image.title="AgentD policy proxy"
LABEL org.opencontainers.image.version="${AGENTD_VERSION}"
LABEL org.opencontainers.image.revision="${AGENTD_COMMIT}"
LABEL org.opencontainers.image.source="https://github.com/danieliser/agentruntime"

COPY squid.conf /etc/squid/squid.conf

EXPOSE 3128
